[package]
name = "rpcore-stream"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rpcore-core = { path = "../rpcore-core" }

bytes = "1"
socket2 = "0.5"

[features]

[[example]]
name = "my-protocol"
path = "examples/my-protocol.rs"
